fix: testing comment in pr

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,14 +43,31 @@ jobs:
         json_data=$(echo -n  $FILES | jq -R -s '{ javaFiles: split(" ") | map(select(test("\\.java$")))}')
         echo $json_data
         curl -LOk https://github.com/google/google-java-format/releases/download/v1.18.1/google-java-format-1.18.1-all-deps.jar
+
+        differing_files=()
         
         for file in $(echo "$json_data" | jq -r '.javaFiles[]'); do 
           java -jar google-java-format-1.18.1-all-deps.jar "$file" > "${file}_formatted"
           if ! cmp -s "$formatted_file" "$file"; then
             echo "$file is not properly formatted"
+            differing_files+=("$formatted_file")            
           fi
         done
 
+        if [ ${#differing_files[@]} -gt 0 ]; then
+         comment="Suggested code formatting changes:"
+          for file in "${differing_files[@]}"; do
+            comment+="\n\n### ${file}\n\`\`\`java\n$(cat "$file")\n\`\`\`"
+          done
 
-        
+          # Print the comment
+          echo "$comment"
+          gh pr comment ${{ github.event.number }} -b $comment
+          
+          echo "::error::Code formatting suggestion detected. Please review and apply the suggested changes."
+          exit 1
+        else
+          # No differing files, exit successfully
+          exit 0
+        fi        
         
